//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soundbase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelSoundbaseContainer : DbContext
    {
        public ModelSoundbaseContainer()
            : base("name=ModelSoundbaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Song> SongSet { get; set; }
        public virtual DbSet<Composer> ComposerSet { get; set; }
        public virtual DbSet<Genre> GenreSet { get; set; }
        public virtual DbSet<Writer> WriterSet { get; set; }
        public virtual DbSet<OfficialVideo> OfficialVideoSet { get; set; }
        public virtual DbSet<Engineer> EngineerSet { get; set; }
        public virtual DbSet<Artist> ArtistSet { get; set; }
        public virtual DbSet<Band> BandSet { get; set; }
        public virtual DbSet<RecordLabel> RecordLabelSet { get; set; }
        public virtual DbSet<Artwork> ArtworkSet { get; set; }
        public virtual DbSet<Album> AlbumSet { get; set; }
        public virtual DbSet<Created> CreatedSet { get; set; }
        public virtual DbSet<Performed> PerformedSet { get; set; }
    }
}
